---
docker_kernel_min_version: '3.10'

# https://download.docker.com/linux/ubuntu/
docker_repo_distro_ver:
  'eoan': 'disco'
  'disco': 'disco'
  'cosmic': 'cosmic'
  'bionic': 'bionic'
  'artful': 'artful'

docker_versioned_pkg:
  'latest': docker-ce
  '1.11': docker-engine=1.11.2-0~{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '1.12': docker-engine=1.12.6-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '1.13': docker-engine=1.13.1-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '17.03': docker-ce=17.03.2~ce-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '17.09': docker-ce=17.09.0~ce-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '17.12': docker-ce=17.12.1~ce-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '18.06': docker-ce=18.06.2~ce~3-0~ubuntu
  '18.09': docker-ce=5:18.09.7~3-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  '19.03': docker-ce=5:19.03.3~3-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  'stable': docker-ce=5:19.03.3~3-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
  'edge': docker-ce=5:18.09.7~3-0~ubuntu-{{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}


docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

docker_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_ubuntu_repo_gpgkey }}'
  repo_keys:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

docker_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ docker_ubuntu_repo_base_url }}
       {{ docker_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
       stable

dockerproject_repo_key_info:
  pkg_key: apt_key
  url: '{{ docker_debian_repo_gpgkey }}'
  repo_keys:
    - 58118E89F3A912897C070ADBF76221572C52609D

dockerproject_repo_distro_ver:
  'eoan': 'disco'
  'disco': 'disco'
  'cosmic': 'cosmic'
  'bionic': 'bionic'
  'artful': 'artful'

dockerproject_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ dockerproject_apt_repo_base_url }}
       {{ ansible_distribution|lower }}-{{ dockerproject_repo_distro_ver[ ansible_distribution_release | lower | string ] }}
       main
